### ISSUE TITLE
One or more required directories are missing - WorldMap & TalentFrame

### ISSUE THREAD

**Issue by OXYDER** [Sarjuuk/aowow#122]
Everything works fine except the step of converting maps from BLP to PNG.
The script can not find the location of the blp / WorldMap and / TalentFrame files.

It so happens that the files are exactly in the right place.

After trying everything and redoing over 20 times I thought there was a problem.

Could this be a problem with the locales path "frFR" in the file "complexImg.func.php"?

Thx.

![compleximgfilegen](https://user-images.githubusercontent.com/1058557/28090000-d9fb0cb2-6658-11e7-8c4f-6d49641a3b86.jpg)

**Comment by Sarjuuk** [comment]
Converting BLPs to PNG is optional, in case the output images are distorted or fragmented and has to be done manually.

The curious case of undetectable extracted files isn't really new, but I thought the last rewrite git rid of it. I'm kind of busy right now with no sign of relief before late august. So I won't really be able to fix it in a timely fashion.

A couple of things from the top of my head you may want to try/check
* the directories are present, but do they have content? 
* is php allowed to read said directories
* try changing the locale prefix. It should throw a warning and the choice to use the wrong locale instead of omitting the files. (e.g. frFR -> enUS)

**Comment by OXYDER** [comment]
Ok, as you mentioned, I renamed my folder to **enUS** and redo the **--firstrun** and it worked. The images are now converted. I renamed my folder **enUS** in **static / images / wow / maps** to **frFR** and is now ready and functional.

_Thank you Sarjuuk and good continuation for aowow! Really a beautiful project!_
