### ISSUE TITLE
some errors with sounds

### ISSUE THREAD

**Issue by PaulTinnick** [Sarjuuk/aowow#138]
![image](https://user-images.githubusercontent.com/26941068/30121843-6e0d3f20-9335-11e7-9127-0d888e502d0e.png)

**Comment by Sarjuuk** [comment]
![image](http://vignette2.wikia.nocookie.net/r2d/images/e/e1/Y_tho.jpg/revision/latest)

**Comment by PaulTinnick** [comment]
In what sense?

**Comment by PaulTinnick** [comment]
I think that the last correction was not required. Possible cause - <locate> in the path to the file

**Comment by Sarjuuk** [comment]
In every sense. I too can post effort-free pictures of questionable value.

You didn't provide any information other that "doesn't work". Not very helpful in analyzing the problem.
Well guess what. It worked for me. Is that helpful to you?  

> \<locale>  

since sounds are locale-independent this setup step checks every locale it knows for sounds .. shortened to this expression.

> .wav_

that's the expected ending; this is fine.

So, do you have any of those files in any of those directories? Substitute \<locale> with enus, engb, frfr, dede, eses, esmx or ruru as needed.

If not, why, not don't you.

**Comment by Magnifikator** [comment]
May a problem can be if you have only one [locale] data but not enUS. In that case it doesn't worked well for me. After that I extracted enGB data as well, renamed them to enUS, activated both languages and than I had more luck.
However all sounds was in English. It seems that aowow doesn't support locale sounds.
So I copied my deDE sounds to enUS sounds and run the firstrun again and then it was ok.

**Comment by peycho** [comment]
I guess this has something to do with this change: https://github.com/Sarjuuk/aowow/commit/dbb4ad0b2ae82fcfd8763118933c54b054732d9b

Apparently ffmpeg can not use .wav_ as output extension and throw errors. Then the second command delete the original files and these sounds are lost until you extract the MPQ files again.

The other reason can be that you're not re-encode sounds with this script: 
https://gist.github.com/Sarjuuk/d77b203f7b71d191509afddabad5fc9f

Here is what I did to make sounds works again (Under Linux). Sorry I'm not using Windows.
I revert this change in my code.
Re-extract all files from MPQ archives.
Re-encode the sound files with the old commands

```
find -name "*.wav" | xargs -I % sh -c 'ffmpeg -hide_banner -y -i "%" -acodec libvorbis "%.ogg"; rm "%";'
find -name "*.mp3" | xargs -I % sh -c 'ffmpeg -hide_banner -y -i "%" -f mp3 -acodec libmp3lame "%.mp3"; rm "%";'
```
Now all sounds looks good in my site. Of course this tool a lot of time to process all sounds.

![image](https://user-images.githubusercontent.com/170853/31682353-7df7abf6-b382-11e7-9f36-8b9307ae0f3a.png)

**Comment by Sarjuuk** [comment]
closed due to age. sorry :(
