### ISSUE TITLE
Where should I make the settings?

### ISSUE THREAD

**Issue by blacknightt1** [Sarjuuk/aowow#324]
Hello
I want to bring the Drops option in the first part
Namely 1: Drops
2: Abilities
3: Controlled abilities
4: Pickpocketing
5: Sounds
6: Comments
7: Screenshots

Where should I make the settings?

![sshot-1](https://user-images.githubusercontent.com/73441575/145776699-1a4f1356-ef88-4c8c-9290-7f3c78953e52.jpg)

**Comment by Sarjuuk** [comment]
There is no setting, it has to be changed manually.
Each page has an unordered list (php array) `lvTabs` of listview tabs. This means the order of adding them to the variable determines the order of display.

So instead of appending the loot tab to the end of the list like this: https://github.com/Sarjuuk/aowow/blob/541224f87bca88995b9721ced0b270d91b73015c/pages/npc.php#L740
it would have to be [added to the front](https://www.php.net/manual/de/function.array-unshift.php):
```php
array_unshift($this->lvTabs, ['item', $tabData]);
```

just take note, that you have up to four loot tabs for each difficulty mode. Also this replacement has to be done on every page that displays loot.

**Comment by blacknightt1** [comment]
Hello
 `array_unshift($this->lvTabs, ['item', $tabData]);`

This code that you gave hides the drop item of some npc

For example: /?npc=14229

It drops 338 items by entering this code, this part is hidden, but I click on /?npc=2545
I tested it and it works fine

**Comment by blacknightt1** [comment]
> There is no setting, it has to be changed manually. Each page has an unordered list (php array) `lvTabs` of listview tabs. This means the order of adding them to the variable determines the order of display.
> 
> So instead of appending the loot tab to the end of the list like this:
> 
> https://github.com/Sarjuuk/aowow/blob/541224f87bca88995b9721ced0b270d91b73015c/pages/npc.php#L740
> 
> it would have to be [added to the front](https://www.php.net/manual/de/function.array-unshift.php):
> 
> ```
> array_unshift($this->lvTabs, ['item', $tabData]);
> ```
> 
> just take note, that you have up to four loot tabs for each difficulty mode. Also this replacement has to be done on every page that displays loot.

Hello
array_unshift($this->lvTabs, ['item', $tabData]);

This code that you gave hides the drop item of some npc

For example: /?npc=14229

It drops 338 items by entering this code, this part is hidden, but I click on /?npc=2545
I tested it and it works fine
