### ISSUE TITLE
Sounds generation: PHP fatal error

### ISSUE THREAD

**Issue by Endalaust** [Sarjuuk/aowow#87]
Hello Sarjuuk,

After sounds extract and convert files, update failed like this:
https://lut.im/db22jWFZxt/9fO11yhDZyK1th5Z.png

Thanks a lot

**Comment by Sarjuuk** [comment]
should be fixed in c85ba1a208a4edb282fdfdfb7affe29ff00dffd8

**Comment by Endalaust** [comment]
Well. Not the same anyway..
https://lut.im/NWMPVPZBlE/LphF6Xh8Og3yhwae.png

**Comment by Sarjuuk** [comment]
i assume you used `php aowow--firstrun`? in this case this error makes no bloody sense. It works for me :/

But i also noticed i forgot to add sounds and soundfiles generators to the firstrun script. (added in efe7b468c91efaa338a6e7bda81554ed5e72f1d5)

maybe just retry it with that.

**Comment by Endalaust** [comment]
Nope, it's php aowow --update
I'll try in few minutes with this update

**Comment by Endalaust** [comment]
Well https://lut.im/IoGc07pe5e/dY4WPvA2W8Hj3zfz.png

**Comment by Sarjuuk** [comment]
yay .. also forgot to retcon the function name in the sql-update file.
it tries to find generator sounds that i just renamed to soundfiles because if the naming conflict in your first post.
hm, probably for the better. also go into your aowow_dbversion table and delete `sounds` FROM from the `build` column

**Comment by Endalaust** [comment]
Well, after firstrun, nothing changes..
https://lut.im/eZmgOe6HFg/0FHbyCKAOBMXrfHj.png

**Comment by Endalaust** [comment]
Thanks. All is OK now
