### ISSUE TITLE
Translation: Class in French

### ISSUE THREAD

**Issue by Endalaust** [Sarjuuk/aowow#91]
I can not find you on irc since few days ago

Class in French : https://pastebin.com/6Wqm72gv
Preview : https://woehead.way-of-elendil.fr/?classes

**Comment by Sarjuuk** [comment]
tyvm,
though there were three minor things:
Death Knight: i believe there is a space missing `..?spells=7.6.770]ont une grande...`
Mage: i changed the portal link to spells-search instead of general search
Paladin: the blessings link still uses the term "blessing" and finds nothing. I used "bénédiction" instead.

**Comment by Endalaust** [comment]
Right, did you edit directly or you want v2 ?

**Comment by Sarjuuk** [comment]
Already did. I just wanted to check back for a second opinion.

**Comment by Sarjuuk** [comment]
added in e400155a64b79aea97189b6242cef3d22da51c71

thx again
